### ISSUE TITLE
Multi-word function declaration does not work as described

### ISSUE THREAD

**Issue by jaderoca** [tim-hardcastle/Charm#2]
In the file examples/functions.ch, there is a function declaration with a two word name (is even). According to the example of usage in the documentation/tutorial, this should work as is.

I get "Error: Charm wasn't expecting 'is' at line 1:2-4 of REPL input." 

If I modify the function declaration to remove the space (iseven), then it works correctly.

Charm 0.3.7
Pop!_OS 22.04 LTS (Ubuntu derivative)
Charm compiled using go version 1.19.5 linux/amd64

I suppose this could be documentation/tutorial error rather than an implementation bug.

**Comment by tim-hardcastle** [comment]
Thanks! It was an implementation bug, and I've fixed it.
