### ISSUE TITLE
Not yet any releases, git tags, or CHANGELOG.

### ISSUE THREAD

**Issue by phlummox** [tim-hardcastle/Charm#5]
(Not that it matters too much *yet* ... but it will as soon as people start using the language, which presumably is the hope.)

I saw there's no CHANGELOG, saying what has changed between versions, and no git tags or releases for the various versions. It might be worth adding these, at least from this version (0.4.0) onwards, so that users can easily tell what has changed from version to version. There's a reasonably sensible format for changelogs at <https://keepachangelog.com>, if you don't already have a preference.

**Comment by tim-hardcastle** [comment]
Thanks. No-one besides me has been using it up 'til now, but as you say, I hope the time will come. I'll make a CHANGELOG from here on out.

**Comment by tim-hardcastle** [comment]
Thanks. No-one besides me has been using it up 'til now, but as you say, I hope the time will come. I'll make a CHANGELOG from here on out.
